###############################
#
# Makefile for Triple Chorus
# based on the work of falkTX
# 
# for full licence, see LICENCE in the root of the project
#
###############################

NAME = TripleChorus

FILES_DSP = triplechorus.cpp
include ../dpf/Makefile.plugins.mk

TARGETS += vst2 vst3 jack lv2_dsp

all: $(TARGETS)


